# Generated by Django 4.2.2 on 2023-07-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('pw', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', '남자'), ('F', '여자')], max_length=1)),
                ('age', models.CharField(choices=[(10, '10대'), (20, '20대'), (30, '30대'), (40, '40대'), (50, '50대'), (60, '60대')], max_length=3)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
