# Generated by Django 4.2.2 on 2023-07-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('reception_time', models.CharField(choices=[(0, '오전 7시'), (1, '오후 5시')], max_length=1)),
                ('weekend', models.CharField(choices=[(0, '주말메일 받지 않기'), (1, '주말에도 메일 받기')], max_length=1)),
                ('book_service', models.CharField(choices=[(0, '도서 서비스 받지 않기'), (1, '도서 서비스 구독 하기')], max_length=1)),
            ],
        ),
    ]
