# Generated by Django 3.1.3 on 2023-07-04 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_bookservice_useroption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Female10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agender_rank', models.IntegerField(blank=True, null=True)),
                ('agender_isbn', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'female_10',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Female20',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agender_rank', models.IntegerField(blank=True, null=True)),
                ('agender_isbn', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'female_20',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Female30',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agender_rank', models.IntegerField(blank=True, null=True)),
                ('agender_isbn', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'female_30',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Female40',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agender_rank', models.IntegerField(blank=True, null=True)),
                ('agender_isbn', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'female_40',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Female50',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agender_rank', models.IntegerField(blank=True, null=True)),
                ('agender_isbn', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'female_50',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Female60',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agender_rank', models.IntegerField(blank=True, null=True)),
                ('agender_isbn', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'female_60',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gyobo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('genre_1', models.CharField(blank=True, max_length=200, null=True)),
                ('genre_2', models.CharField(blank=True, max_length=300, null=True)),
                ('brank', models.SmallIntegerField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('count', models.SmallIntegerField(blank=True, null=True)),
                ('isbn', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gyobo_기타',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gyobo01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('large_category', models.CharField(blank=True, max_length=200, null=True)),
                ('middle_category', models.CharField(blank=True, max_length=300, null=True)),
                ('b_rank', models.SmallIntegerField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('count', models.SmallIntegerField(blank=True, null=True)),
                ('isbn', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gyobo_소설',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gyobo03',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('large_category', models.CharField(blank=True, max_length=200, null=True)),
                ('middle_category', models.CharField(blank=True, max_length=300, null=True)),
                ('b_rank', models.SmallIntegerField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('count', models.SmallIntegerField(blank=True, null=True)),
                ('isbn', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gyobo_시에세이',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gyobo05',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('large_category', models.CharField(blank=True, max_length=200, null=True)),
                ('middle_category', models.CharField(blank=True, max_length=300, null=True)),
                ('b_rank', models.SmallIntegerField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('count', models.SmallIntegerField(blank=True, null=True)),
                ('isbn', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gyobo_인문',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gyobo13',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('large_category', models.CharField(blank=True, max_length=200, null=True)),
                ('middle_category', models.CharField(blank=True, max_length=300, null=True)),
                ('b_rank', models.SmallIntegerField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('count', models.SmallIntegerField(blank=True, null=True)),
                ('isbn', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gyobo_경제경영',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gyobo15',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('large_category', models.CharField(blank=True, max_length=200, null=True)),
                ('middle_category', models.CharField(blank=True, max_length=300, null=True)),
                ('b_rank', models.SmallIntegerField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('count', models.SmallIntegerField(blank=True, null=True)),
                ('isbn', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gyobo_자기계발',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gyobo17',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('large_category', models.CharField(blank=True, max_length=200, null=True)),
                ('middle_category', models.CharField(blank=True, max_length=300, null=True)),
                ('b_rank', models.SmallIntegerField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('count', models.SmallIntegerField(blank=True, null=True)),
                ('isbn', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gyobo_정치사회',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gyobo19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('large_category', models.CharField(blank=True, max_length=200, null=True)),
                ('middle_category', models.CharField(blank=True, max_length=300, null=True)),
                ('b_rank', models.SmallIntegerField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('count', models.SmallIntegerField(blank=True, null=True)),
                ('isbn', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gyobo_역사문화',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gyobo23',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('large_category', models.CharField(blank=True, max_length=200, null=True)),
                ('middle_category', models.CharField(blank=True, max_length=300, null=True)),
                ('b_rank', models.SmallIntegerField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('count', models.SmallIntegerField(blank=True, null=True)),
                ('isbn', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gyobo_예술대중문화',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gyobo29',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('large_category', models.CharField(blank=True, max_length=200, null=True)),
                ('middle_category', models.CharField(blank=True, max_length=300, null=True)),
                ('b_rank', models.SmallIntegerField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('count', models.SmallIntegerField(blank=True, null=True)),
                ('isbn', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gyobo_과학',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Male10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agender_rank', models.IntegerField(blank=True, null=True)),
                ('agender_isbn', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'male_10',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Male20',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agender_rank', models.IntegerField(blank=True, null=True)),
                ('agender_isbn', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'male_20',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Male30',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agender_rank', models.IntegerField(blank=True, null=True)),
                ('agender_isbn', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'male_30',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Male40',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agender_rank', models.IntegerField(blank=True, null=True)),
                ('agender_isbn', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'male_40',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Male50',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agender_rank', models.IntegerField(blank=True, null=True)),
                ('agender_isbn', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'male_50',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Male60',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agender_rank', models.IntegerField(blank=True, null=True)),
                ('agender_isbn', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'male_60',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', '남자'), ('F', '여자')], max_length=1)),
                ('age', models.IntegerField(choices=[(10, '10대'), (20, '20대'), (30, '30대'), (40, '40대'), (50, '50대'), (60, '60대')])),
            ],
            options={
                'db_table': 'user_info',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='BookService',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterModelOptions(
            name='useroption',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='BookOption',
            fields=[
                ('email', models.OneToOneField(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='common.userinfo')),
                ('book_service', models.IntegerField()),
                ('large_category', models.CharField(blank=True, max_length=200, null=True)),
                ('middle_category', models.CharField(blank=True, max_length=300, null=True)),
                ('selected_book_isbn', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'book_option',
                'managed': False,
            },
        ),
    ]
