# Generated by Django 3.1.3 on 2023-07-04 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20230704_1246'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useroption',
            table='user_option',
        ),
    ]
